<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Carla Fernández Alcázar
Curso: DAW1
Fecha: 02/04/2025
Ejercicio: Ejercicio 5
-->

<!DOCTYPE reyesEspañoles [
    <!ELEMENT reyesEspañoles (rey*, reina*)>
    <!ELEMENT rey (nombre, padre, madre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT padre (#PCDATA)>
    <!ELEMENT madre (#PCDATA)>
    <!ELEMENT reina (nombre, padre, madre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT padre (#PCDATA)>
    <!ELEMENT madre (#PCDATA)>
]>

<reyesEspañoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    
    <reina>
        <nombre>Juana la Loca</nombre>
        <padre>Fernando el Catolico</padre>
        <madre>Isabel la Catolica</madre>
    </reina>

    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juana la Loca</madre>
    </rey>
</reyesEspañoles>